version: 2.1
orbs:
  slack: circleci/slack@4.9.3
commands:
  fbz_notify_start:
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Job Start.",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Project*: $CIRCLE_PROJECT_REPONAME"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*: $CIRCLE_BRANCH"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit*: $CIRCLE_SHA1"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author*: $CIRCLE_USERNAME"
                    }
                  ],
                  "accessory": {
                    "type": "image",
                    "image_url": "https://cdn.financebuzz.com/assets/2017/08/28/favicon.png",
                    "alt_text": "Financebuzz"
                  }
                }
              ]
            }
          event: always
  fbz_notify_failed:
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Job Failed. :red_circle:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Job*: ${CIRCLE_JOB}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Project*: $CIRCLE_PROJECT_REPONAME"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*: $CIRCLE_BRANCH"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit*: $CIRCLE_SHA1"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author*: $CIRCLE_USERNAME"
                    }
                  ],
                  "accessory": {
                    "type": "image",
                    "image_url": "https://cdn.financebuzz.com/assets/2017/08/28/favicon.png",
                    "alt_text": "Financebuzz"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}"
                    }
                  ]
                }
              ]
            }
          event: fail
  fbz_notify_finish:
    steps:
      - slack/notify:
            custom: |
              {
                "blocks": [
                  {
                    "type": "header",
                    "text": {
                      "type": "plain_text",
                      "text": "Job Finish. :white_check_mark:",
                      "emoji": true
                    }
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Project*: $CIRCLE_PROJECT_REPONAME"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*When*: $(date +'%m/%d/%Y %T')"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Commit*: $CIRCLE_SHA1"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Author*: $CIRCLE_USERNAME"
                      }
                    ],
                    "accessory": {
                      "type": "image",
                      "image_url": "https://cdn.financebuzz.com/assets/2017/08/28/favicon.png",
                      "alt_text": "Financebuzz"
                    }
                  }
                ]
              }
            event: pass
jobs:
  checkout_code_and_run_test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: echo 'checkout'
      - fbz_notify_start

  build_image:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: echo 'build image'
      - fbz_notify_failed
  
  push_image:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: echo 'push image'
      - fbz_notify_failed
  
  migration:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: echo 'running migration'
      - fbz_notify_failed
  
  update_celery:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: echo 'update celery'
      - fbz_notify_failed

  update_webservers:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: echo 'update web server'
      - fbz_notify_failed
      - fbz_notify_finish

workflows:
  build-test-and-deploy:
    jobs:
      - checkout_code_and_run_test
          context: slack-secrets
      - migration:
          requires:
            - checkout_code_and_run_test
          context: slack-secrets
      - update_celery:
          requires:
            - migration
          context: slack-secrets
      - update_webservers:
          requires:
            - update_celery
          context: slack-secrets

