version: 2.1
orbs:
  slack: circleci/slack@4.9.3
commands:
  fbz_notify_start:
    steps:
      - checkout
      - run: echo 'export FBZ_TEMPLATE_START=$(jq .start ./.circleci/slack_templates.json)' >> $BASH_ENV
      - run: echo 'export GIT_COMMIT_MESSAGE="$(git log --format=%B -n 1 $CIRCLE_SHA1)"' >> $BASH_ENV
      - slack/notify:
          event: always
          template: FBZ_TEMPLATE_START
  fbz_notify_failed:
    steps:
      - checkout
      - run: echo 'export FBZ_TEMPLATE_FAIL=$(jq .fail ./.circleci/slack_templates.json)' >> $BASH_ENV
      - run: echo 'export GIT_COMMIT_MESSAGE="$(git log --format=%B -n 1 $CIRCLE_SHA1)"' >> $BASH_ENV
      - slack/notify:
          event: fail
          template: FBZ_TEMPLATE_FAIL
  fbz_notify_finish:
    steps:
      - checkout
      - run: echo 'export FBZ_TEMPLATE_PASS=$(jq .pass ./.circleci/slack_templates.json)' >> $BASH_ENV
      - run: echo 'export GIT_COMMIT_MESSAGE="$(git log --format=%B -n 1 $CIRCLE_SHA1)"' >> $BASH_ENV
      - slack/notify:
          event: pass
          template: FBZ_TEMPLATE_PASS
jobs:
  checkout_code_and_run_test:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo 'checkout'

  build_image:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo 'build image'
      - fbz_notify_failed
  
  push_image:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo 'push image'
      - fbz_notify_failed
  
  migration:
    docker:
      - image: cimg/base:stable
    steps:
      - fbz_notify_start
      - run: echo 'running migration'
      - fbz_notify_failed
  
  update_celery:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo 'update celery'
      - fbz_notify_failed

  update_webservers:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo 'update web server'
      - fbz_notify_failed
      - fbz_notify_finish

workflows:
  build-test-and-deploy:
    jobs:
      - checkout_code_and_run_test
      - migration:
          requires:
            - checkout_code_and_run_test
          context: slack-secrets
      - update_celery:
          requires:
            - migration
          context: slack-secrets
      - update_webservers:
          requires:
            - update_celery
          context: slack-secrets

