version: 2.1
orbs:
  slack: circleci/slack@4.9.3
jobs:
  checkout_code_and_run_test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*Deploy start*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
      - run: echo 'checkout'

  build_image:
    steps:
      - run: echo 'build image'
  
  push_image:
    steps:
      - run: echo 'push image'
  
  migration:
    steps:
      - run: echo 'running migration'
  
  update_celery:
    steps:
      - run: echo 'update celery'

  update_webservers:
    steps:
      - run: echo 'update web server'
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*Deploy finish*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always

workflows:
  build-test-and-deploy:
    jobs:
      - checkout_code_and_run_test:
          context: slack-secrets
      - migration
      - update_celery
      - update_webservers:
          context: slack-secrets
